INSERT INTO ROLE_TABLE VALUES ( 1, 'User')

INSERT INTO ACTIVITY_TABLE VALUES (1, 'Activity01')
INSERT INTO ACTIVITY_TABLE VALUES (2, 'Activity02')
INSERT INTO ACTIVITY_TABLE VALUES (3, 'Activity03')
INSERT INTO ACTIVITY_TABLE VALUES (4, 'Activity04')
INSERT INTO ACTIVITY_TABLE VALUES (5, 'Activity05')

INSERT INTO USER_TABLE VALUES (1, 'name', '$2a$10$sbLRDIGdFCQ/.46x6v3UAudUJILlgyZfzfyKKNx6Q2dct9cagvAPu', 'surname', 'code', 1)

INSERT INTO ISSUE_TABLE VALUES(1, '15:30 09/10', 'Description', FALSE, 'Title 01', 1, 1)
INSERT INTO ISSUE_TABLE VALUES(2, '15:30 09/10', 'Description', FALSE, 'Title 02', 1, 1)
INSERT INTO ISSUE_TABLE VALUES(3, '15:30 09/10', 'Description', FALSE, 'Title 03', 1, 1)

